// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCategory = "category"

// Category 分类
type Category struct {
	ID        uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid       int            `gorm:"column:pid;not null;comment:PId" json:"pid"`                  // PId
	IsMenu    uint           `gorm:"column:is_menu;not null;comment:是菜单：1=是, 2=否" json:"is_menu"` // 是菜单：1=是, 2=否
	Title     string         `gorm:"column:title;not null;comment:标题" json:"title"`               // 标题
	Icon      string         `gorm:"column:icon;not null;comment:图标" json:"icon"`                 // 图标
	Status    uint           `gorm:"column:status;not null;comment:状态：1=正常, 2=禁用" json:"status"`  // 状态：1=正常, 2=禁用
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
