// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameImage = "image"

// Image 图片
type Image struct {
	ID           uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title        string         `gorm:"column:title;not null;comment:标题" json:"title"`                              // 标题
	ListSmallURL string         `gorm:"column:list_small_url;not null;comment:列表缩略图" json:"list_small_url"`         // 列表缩略图
	SmallURL     string         `gorm:"column:small_url;not null;comment:详情缩略图" json:"small_url"`                   // 详情缩略图
	OriginURL    string         `gorm:"column:origin_url;not null;comment:原图" json:"origin_url"`                    // 原图
	Size         uint           `gorm:"column:size;not null;comment:原图大小 byte" json:"size"`                         // 原图大小 byte
	Weight       uint           `gorm:"column:weight;not null;comment:原图宽 像素" json:"weight"`                        // 原图宽 像素
	High         uint           `gorm:"column:high;not null;comment:原图高 像素" json:"high"`                            // 原图高 像素
	Type         string         `gorm:"column:type;not null;comment:原图类型" json:"type"`                              // 原图类型
	IsFree       uint           `gorm:"column:is_free;not null;comment:免费：1=是，2=否，3=未知" json:"is_free"`             // 免费：1=是，2=否，3=未知
	Keyword      string         `gorm:"column:keyword;not null;comment:关键字(多个逗号分隔)" json:"keyword"`                 // 关键字(多个逗号分隔)
	Source       uint           `gorm:"column:source;not null;comment:来源：1=游戏，2=movie，3=后台上传，4=ai生成" json:"source"` // 来源：1=游戏，2=movie，3=后台上传，4=ai生成
	SourceID     uint           `gorm:"column:source_id;not null;comment:来源ID" json:"source_id"`                    // 来源ID
	SourceCode   string         `gorm:"column:source_code;not null;comment:来源code" json:"source_code"`              // 来源code
	Status       uint           `gorm:"column:status;not null;comment:状态：1=正常，2=审核中，3=审核拒绝，4=禁用" json:"status"`     // 状态：1=正常，2=审核中，3=审核拒绝，4=禁用
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
