// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUsers = "users"

// Users 用户
type Users struct {
	ID              uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Avatar          string         `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                              // 头像
	Nickname        string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                          // 昵称
	Email           string         `gorm:"column:email;not null;comment:邮箱" json:"email"`                                // 邮箱
	EmailVerifiedAt *time.Time     `gorm:"column:email_verified_at;comment:邮箱验证时间" json:"email_verified_at"`             // 邮箱验证时间
	Password        string         `gorm:"column:password;not null;comment:密码" json:"password"`                          // 密码
	Status          int            `gorm:"column:status;not null;comment:状态:1=正常,2=待激活,3=禁止登录,4=禁用,5=注销," json:"status"` // 状态:1=正常,2=待激活,3=禁止登录,4=禁用,5=注销,
	RememberToken   *string        `gorm:"column:remember_token" json:"remember_token"`
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Users's table name
func (*Users) TableName() string {
	return TableNameUsers
}
