// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameArticle = "article"

// Article 文章
type Article struct {
	ID              uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IsDraft         uint           `gorm:"column:is_draft;not null;comment:草稿: 1=是, 2=否," json:"is_draft"`                                    // 草稿: 1=是, 2=否,
	DraftFromID     int            `gorm:"column:draft_from_id;not null;comment:草稿来源ID: 0表示需要新建" json:"draft_from_id"`                        // 草稿来源ID: 0表示需要新建
	DraftStatus     uint           `gorm:"column:draft_status;not null;comment:状态: 1=已同步, 2=审核中, 3=审核拒绝, 4=审核通过待同步" json:"draft_status"`      // 状态: 1=已同步, 2=审核中, 3=审核拒绝, 4=审核通过待同步
	SmallTitle      string         `gorm:"column:small_title;not null;comment:简略标题" json:"small_title"`                                       // 简略标题
	SmallImage      string         `gorm:"column:small_image;not null;comment:简略图" json:"small_image"`                                        // 简略图
	Title           string         `gorm:"column:title;not null;comment:标题" json:"title"`                                                     // 标题
	BackgroundImage string         `gorm:"column:background_image;not null;comment:背景图" json:"background_image"`                              // 背景图
	ContentType     uint           `gorm:"column:content_type;not null;comment:内容类型: 1=txt, 2=html, 3=md," json:"content_type"`               // 内容类型: 1=txt, 2=html, 3=md,
	Content         *string        `gorm:"column:content;comment:内容" json:"content"`                                                          // 内容
	ReleaseTime     time.Time      `gorm:"column:release_time;not null;default:CURRENT_TIMESTAMP;comment:发布时间" json:"release_time"`           // 发布时间
	LastModifyTime  time.Time      `gorm:"column:last_modify_time;not null;default:CURRENT_TIMESTAMP;comment:上次编辑时间" json:"last_modify_time"` // 上次编辑时间
	Status          uint           `gorm:"column:status;not null;comment:状态：1=正常, 2=禁用, 3=下架" json:"status"`                                  // 状态：1=正常, 2=禁用, 3=下架
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
