// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSteamGame = "steam_game"

// SteamGame steam游戏
type SteamGame struct {
	ID                      uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CnName                  string         `gorm:"column:cn_name;not null;comment:中文名称" json:"cn_name"`                                               // 中文名称
	Name                    string         `gorm:"column:name;not null;comment:名称" json:"name"`                                                       // 名称
	SteamAppid              string         `gorm:"column:steam_appid;not null;comment:steam_appid" json:"steam_appid"`                                // steam_appid
	Cc                      string         `gorm:"column:cc;not null;comment:cc区" json:"cc"`                                                          // cc区
	L                       string         `gorm:"column:l;not null;comment:语言" json:"l,string"`                                                      // 语言
	HeaderImage             string         `gorm:"column:header_image;not null;comment:缩略图" json:"header_image"`                                      // 缩略图
	CapsuleImage            string         `gorm:"column:capsule_image;not null;comment:列表缩略图" json:"capsule_image"`                                  // 列表缩略图
	CoverImage              string         `gorm:"column:cover_image;not null;comment:封面图" json:"cover_image"`                                        // 封面图
	BackgroundImage         string         `gorm:"column:background_image;not null;comment:背景图" json:"background_image"`                              // 背景图
	ShortDescription        string         `gorm:"column:short_description;not null;comment:一句话简介" json:"short_description"`                          // 一句话简介
	AboutTheGame            *string        `gorm:"column:about_the_game;comment:关于游戏" json:"about_the_game"`                                          // 关于游戏
	DetailDescription       *string        `gorm:"column:detail_description;comment:简介" json:"detail_description"`                                    // 简介
	RequiredAge             uint           `gorm:"column:required_age;not null;comment:年龄限制" json:"required_age"`                                     // 年龄限制
	IsViolent               uint           `gorm:"column:is_violent;not null;comment:包含暴力、血腥内容：1=是，2=否，3=未知" json:"is_violent"`                       // 包含暴力、血腥内容：1=是，2=否，3=未知
	IsSexy                  uint           `gorm:"column:is_sexy;not null;comment:包含色情内容：1=是，2=否，3=未知" json:"is_sexy"`                                // 包含色情内容：1=是，2=否，3=未知
	SupportedLanguages      *string        `gorm:"column:supported_languages;comment:支持的语言" json:"supported_languages"`                               // 支持的语言
	SupportChinese          uint           `gorm:"column:support_chinese;not null;comment:支持中文：1=是，2=否，3=未知" json:"support_chinese"`                  // 支持中文：1=是，2=否，3=未知
	IsFree                  uint           `gorm:"column:is_free;not null;comment:免费：1=是，2=否，3=未知" json:"is_free"`                                    // 免费：1=是，2=否，3=未知
	HaveDic                 uint           `gorm:"column:have_dic;not null;comment:有dlc：1=是，2=否，3=未知" json:"have_dic"`                                // 有dlc：1=是，2=否，3=未知
	DicIds                  string         `gorm:"column:dic_ids;not null;comment:dlc_ids" json:"dic_ids"`                                            // dlc_ids
	PriceCurrency           string         `gorm:"column:price_currency;not null;comment:价格-货币" json:"price_currency"`                                // 价格-货币
	PriceInitial            uint           `gorm:"column:price_initial;not null;comment:价格-原价（分）" json:"price_initial"`                               // 价格-原价（分）
	PriceFinal              uint           `gorm:"column:price_final;not null;comment:价格-现价（分）" json:"price_final"`                                   // 价格-现价（分）
	PriceDiscountPercent    float64        `gorm:"column:price_discount_percent;not null;default:0.00;comment:价格-折扣" json:"price_discount_percent"`   // 价格-折扣
	PriceUnit               string         `gorm:"column:price_unit;not null;comment:价格-单位" json:"price_unit"`                                        // 价格-单位
	Windows                 uint           `gorm:"column:windows;not null;comment:支持windows：1=是，2=否，3=未知" json:"windows"`                             // 支持windows：1=是，2=否，3=未知
	Mac                     uint           `gorm:"column:mac;not null;comment:支持mac：1=是，2=否，3=未知" json:"mac"`                                         // 支持mac：1=是，2=否，3=未知
	Linux                   uint           `gorm:"column:linux;not null;comment:支持linux：1=是，2=否，3=未知" json:"linux"`                                   // 支持linux：1=是，2=否，3=未知
	Network                 uint           `gorm:"column:network;not null;comment:联网：1=是，2=否，3=未知" json:"network"`                                    // 联网：1=是，2=否，3=未知
	Images                  uint           `gorm:"column:images;not null;comment:有图片：1=是，2=否，3=未知" json:"images"`                                     // 有图片：1=是，2=否，3=未知
	Movies                  uint           `gorm:"column:movies;not null;comment:有视频：1=是，2=否，3=未知" json:"movies"`                                     // 有视频：1=是，2=否，3=未知
	Genre                   string         `gorm:"column:genre;not null;comment:类型(多个逗号分隔)" json:"genre"`                                             // 类型(多个逗号分隔)
	Developers              string         `gorm:"column:developers;not null;comment:开发商(多个逗号分隔)" json:"developers"`                                  // 开发商(多个逗号分隔)
	Publishers              string         `gorm:"column:publishers;not null;comment:发行商(多个逗号分隔)" json:"publishers"`                                  // 发行商(多个逗号分隔)
	ContentDescriptorsNotes *string        `gorm:"column:content_descriptors_notes;comment:提醒文案" json:"content_descriptors_notes"`                    // 提醒文案
	ComingSoon              uint           `gorm:"column:coming_soon;not null;comment:已发布：1=是，2=否，3=未知" json:"coming_soon"`                           // 已发布：1=是，2=否，3=未知
	ReleaseDate             string         `gorm:"column:release_date;not null;comment:发布时间" json:"release_date"`                                     // 发布时间
	ReleaseTime             int            `gorm:"column:release_time;not null;comment:发布时间戳" json:"release_time"`                                    // 发布时间戳
	LastModifyTime          time.Time      `gorm:"column:last_modify_time;not null;default:CURRENT_TIMESTAMP;comment:上次更新时间" json:"last_modify_time"` // 上次更新时间
	Status                  uint           `gorm:"column:status;not null;comment:状态：1=正常，2=审核中，3=审核拒绝，4=禁用，5=删除" json:"status"`                       // 状态：1=正常，2=审核中，3=审核拒绝，4=禁用，5=删除
	Used                    uint           `gorm:"column:used;not null;comment:状态：1=已使用，2=未使用" json:"used"`                                           // 状态：1=已使用，2=未使用
	CreatedAt               time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt               time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt               gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName SteamGame's table name
func (*SteamGame) TableName() string {
	return TableNameSteamGame
}
