// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSteamGameVideo = "steam_game_video"

// SteamGameVideo steam游戏-视频
type SteamGameVideo struct {
	ID          uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string         `gorm:"column:name;not null;comment:name" json:"name"`                        // name
	SteamGameID uint           `gorm:"column:steam_game_id;not null;comment:steam游戏ID" json:"steam_game_id"` // steam游戏ID
	OriginID    uint           `gorm:"column:origin_id;not null;comment:steam游戏movieID" json:"origin_id"`    // steam游戏movieID
	Thumbnail   string         `gorm:"column:thumbnail;not null;comment:缩略图" json:"thumbnail"`               // 缩略图
	Webm480     string         `gorm:"column:webm_480;not null;comment:webm 480 视频地址" json:"webm_480"`       // webm 480 视频地址
	WebmMax     string         `gorm:"column:webm_max;not null;comment:webm max 视频地址" json:"webm_max"`       // webm max 视频地址
	Mp4480      string         `gorm:"column:mp4_480;not null;comment:mp4 480 视频地址" json:"mp4_480"`          // mp4 480 视频地址
	Mp4Max      string         `gorm:"column:mp4_max;not null;comment:mp4 max 视频地址" json:"mp4_max"`          // mp4 max 视频地址
	Used        uint           `gorm:"column:used;not null;comment:状态：1=已使用，2=未使用" json:"used"`              // 状态：1=已使用，2=未使用
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName SteamGameVideo's table name
func (*SteamGameVideo) TableName() string {
	return TableNameSteamGameVideo
}
