// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSteamGameImage = "steam_game_image"

// SteamGameImage steam游戏-图片
type SteamGameImage struct {
	ID            uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SteamGameID   uint           `gorm:"column:steam_game_id;not null;comment:steam游戏ID" json:"steam_game_id"` // steam游戏ID
	PathThumbnail string         `gorm:"column:path_thumbnail;not null;comment:缩略图" json:"path_thumbnail"`     // 缩略图
	PathFull      string         `gorm:"column:path_full;not null;comment:原图" json:"path_full"`                // 原图
	ImageCode     string         `gorm:"column:image_code;not null;comment:图片标记" json:"image_code"`            // 图片标记
	Used          uint           `gorm:"column:used;not null;comment:状态：1=已使用，2=未使用" json:"used"`              // 状态：1=已使用，2=未使用
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName SteamGameImage's table name
func (*SteamGameImage) TableName() string {
	return TableNameSteamGameImage
}
